os: osx
language: objective-c
osx_image: xcode10.2

env: 
  - JOB=LINT
  - JOB=TEST
  - JOB=POD_LINT

before_script:
  - mkdir -p build
  - swift --version

script:
  - if [ "$JOB" == "LINT" ]; then Scripts/ci_phases/01_lint_project.sh; fi
  - if [ "$JOB" == "TEST" ]; then travis_retry Scripts/ci_phases/02_run_tests_ios.sh; fi
  - if [ "$JOB" == "POD_LINT" ]; then bundle exec pod lib lint  --sources=https://cdn.cocoapods.org/ ; fi
