name: Lint

jobs:
  lint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Bundler Cache
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Pods Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cocoapods
          ~/Library/Caches/CocoaPods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - name: Pods
      run: |
        bundle exec pod install

    - name: Lint
      run: |
        Scripts/ci_phases/01_lint_project.sh

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
