name: Pod Lib

jobs:
  pod-lib:
    strategy:
      fail-fast: false
      matrix:
        platform: [ios, watchos, macos]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: setup-xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 11.7
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - run: echo "ImageVersion=$ImageVersion" >> $GITHUB_ENV
    - name: Bundler Cache
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-${{ env.ImageVersion }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.ImageVersion }}-gems-
    - name: bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Pods Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cocoapods
          ~/Library/Caches/CocoaPods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile') }}
        restore-keys: |
          ${{ runner.os }}-pods-

    - name: pod lib lint
      run: |
        bundle exec pod lib lint --platforms=${{ matrix.platform }} --no-subspecs --verbose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '0 9 * * 0,1,2,3,4'
      branches:
      - main
